//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mRemoteUG {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size MainFormSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFormSize"]));
            }
            set {
                this["MainFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainFormState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainFormState"]));
            }
            set {
                this["MainFormState"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainFormDpi {
            get {
                return ((int)(this["MainFormDpi"]));
            }
            set {
                this["MainFormDpi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainFormKiosk {
            get {
                return ((bool)(this["MainFormKiosk"]));
            }
            set {
                this["MainFormKiosk"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DoUpgrade {
            get {
                return ((bool)(this["DoUpgrade"]));
            }
            set {
                this["DoUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomPuttyPath {
            get {
                return ((string)(this["CustomPuttyPath"]));
            }
            set {
                this["CustomPuttyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SwitchToMCOnInformation {
            get {
                return ((bool)(this["SwitchToMCOnInformation"]));
            }
            set {
                this["SwitchToMCOnInformation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SwitchToMCOnWarning {
            get {
                return ((bool)(this["SwitchToMCOnWarning"]));
            }
            set {
                this["SwitchToMCOnWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SwitchToMCOnError {
            get {
                return ((bool)(this["SwitchToMCOnError"]));
            }
            set {
                this["SwitchToMCOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LoadConsFromCustomLocation {
            get {
                return ((bool)(this["LoadConsFromCustomLocation"]));
            }
            set {
                this["LoadConsFromCustomLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomConsPath {
            get {
                return ((string)(this["CustomConsPath"]));
            }
            set {
                this["CustomConsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveConsOnExit {
            get {
                return ((bool)(this["SaveConsOnExit"]));
            }
            set {
                this["SaveConsOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDescriptionTooltipsInTree {
            get {
                return ((bool)(this["ShowDescriptionTooltipsInTree"]));
            }
            set {
                this["ShowDescriptionTooltipsInTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSystemTrayIcon {
            get {
                return ((bool)(this["ShowSystemTrayIcon"]));
            }
            set {
                this["ShowSystemTrayIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenTabsRightOfSelected {
            get {
                return ((bool)(this["OpenTabsRightOfSelected"]));
            }
            set {
                this["OpenTabsRightOfSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLogonInfoOnTabs {
            get {
                return ((bool)(this["ShowLogonInfoOnTabs"]));
            }
            set {
                this["ShowLogonInfoOnTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleClickOnConnectionOpensIt {
            get {
                return ((bool)(this["SingleClickOnConnectionOpensIt"]));
            }
            set {
                this["SingleClickOnConnectionOpensIt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("noinfo")]
        public string EmptyCredentials {
            get {
                return ((string)(this["EmptyCredentials"]));
            }
            set {
                this["EmptyCredentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultUsername {
            get {
                return ((string)(this["DefaultUsername"]));
            }
            set {
                this["DefaultUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultPassword {
            get {
                return ((string)(this["DefaultPassword"]));
            }
            set {
                this["DefaultPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultDomain {
            get {
                return ((string)(this["DefaultDomain"]));
            }
            set {
                this["DefaultDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStart {
            get {
                return ((bool)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowProtocolOnTabs {
            get {
                return ((bool)(this["ShowProtocolOnTabs"]));
            }
            set {
                this["ShowProtocolOnTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResetPanels {
            get {
                return ((bool)(this["ResetPanels"]));
            }
            set {
                this["ResetPanels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultDescription {
            get {
                return ((string)(this["ConDefaultDescription"]));
            }
            set {
                this["ConDefaultDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RDP")]
        public string ConDefaultProtocol {
            get {
                return ((string)(this["ConDefaultProtocol"]));
            }
            set {
                this["ConDefaultProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default Settings")]
        public string ConDefaultPuttySession {
            get {
                return ((string)(this["ConDefaultPuttySession"]));
            }
            set {
                this["ConDefaultPuttySession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultUseConsoleSession {
            get {
                return ((bool)(this["ConDefaultUseConsoleSession"]));
            }
            set {
                this["ConDefaultUseConsoleSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FitToWindow")]
        public string ConDefaultResolution {
            get {
                return ((string)(this["ConDefaultResolution"]));
            }
            set {
                this["ConDefaultResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Colors16Bit")]
        public string ConDefaultColors {
            get {
                return ((string)(this["ConDefaultColors"]));
            }
            set {
                this["ConDefaultColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultCacheBitmaps {
            get {
                return ((bool)(this["ConDefaultCacheBitmaps"]));
            }
            set {
                this["ConDefaultCacheBitmaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultDisplayWallpaper {
            get {
                return ((bool)(this["ConDefaultDisplayWallpaper"]));
            }
            set {
                this["ConDefaultDisplayWallpaper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultDisplayThemes {
            get {
                return ((bool)(this["ConDefaultDisplayThemes"]));
            }
            set {
                this["ConDefaultDisplayThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectKeys {
            get {
                return ((bool)(this["ConDefaultRedirectKeys"]));
            }
            set {
                this["ConDefaultRedirectKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectDiskDrives {
            get {
                return ((bool)(this["ConDefaultRedirectDiskDrives"]));
            }
            set {
                this["ConDefaultRedirectDiskDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectPrinters {
            get {
                return ((bool)(this["ConDefaultRedirectPrinters"]));
            }
            set {
                this["ConDefaultRedirectPrinters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectPorts {
            get {
                return ((bool)(this["ConDefaultRedirectPorts"]));
            }
            set {
                this["ConDefaultRedirectPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRedirectSmartCards {
            get {
                return ((bool)(this["ConDefaultRedirectSmartCards"]));
            }
            set {
                this["ConDefaultRedirectSmartCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConDefaultRedirectClipboard {
            get {
                return ((bool)(this["ConDefaultRedirectClipboard"]));
            }
            set {
                this["ConDefaultRedirectClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DoNotPlay")]
        public string ConDefaultRedirectSound {
            get {
                return ((string)(this["ConDefaultRedirectSound"]));
            }
            set {
                this["ConDefaultRedirectSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int MaxPuttyWaitTime {
            get {
                return ((int)(this["MaxPuttyWaitTime"]));
            }
            set {
                this["MaxPuttyWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleInstance {
            get {
                return ((bool)(this["SingleInstance"]));
            }
            set {
                this["SingleInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenConsFromLastSession {
            get {
                return ((bool)(this["OpenConsFromLastSession"]));
            }
            set {
                this["OpenConsFromLastSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoReconnect {
            get {
                return ((bool)(this["NoReconnect"]));
            }
            set {
                this["NoReconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AutoSaveEveryMinutes {
            get {
                return ((int)(this["AutoSaveEveryMinutes"]));
            }
            set {
                this["AutoSaveEveryMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickyTBVisible {
            get {
                return ((bool)(this["QuickyTBVisible"]));
            }
            set {
                this["QuickyTBVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3, 24")]
        public global::System.Drawing.Point QuickyTBLocation {
            get {
                return ((global::System.Drawing.Point)(this["QuickyTBLocation"]));
            }
            set {
                this["QuickyTBLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Top")]
        public string QuickyTBParentDock {
            get {
                return ((string)(this["QuickyTBParentDock"]));
            }
            set {
                this["QuickyTBParentDock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ResetToolbars {
            get {
                return ((bool)(this["ResetToolbars"]));
            }
            set {
                this["ResetToolbars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultCacheBitmaps {
            get {
                return ((bool)(this["InhDefaultCacheBitmaps"]));
            }
            set {
                this["InhDefaultCacheBitmaps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultColors {
            get {
                return ((bool)(this["InhDefaultColors"]));
            }
            set {
                this["InhDefaultColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDescription {
            get {
                return ((bool)(this["InhDefaultDescription"]));
            }
            set {
                this["InhDefaultDescription"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDisplayThemes {
            get {
                return ((bool)(this["InhDefaultDisplayThemes"]));
            }
            set {
                this["InhDefaultDisplayThemes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDisplayWallpaper {
            get {
                return ((bool)(this["InhDefaultDisplayWallpaper"]));
            }
            set {
                this["InhDefaultDisplayWallpaper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultDomain {
            get {
                return ((bool)(this["InhDefaultDomain"]));
            }
            set {
                this["InhDefaultDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultIcon {
            get {
                return ((bool)(this["InhDefaultIcon"]));
            }
            set {
                this["InhDefaultIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPassword {
            get {
                return ((bool)(this["InhDefaultPassword"]));
            }
            set {
                this["InhDefaultPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPort {
            get {
                return ((bool)(this["InhDefaultPort"]));
            }
            set {
                this["InhDefaultPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultProtocol {
            get {
                return ((bool)(this["InhDefaultProtocol"]));
            }
            set {
                this["InhDefaultProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPuttySession {
            get {
                return ((bool)(this["InhDefaultPuttySession"]));
            }
            set {
                this["InhDefaultPuttySession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectDiskDrives {
            get {
                return ((bool)(this["InhDefaultRedirectDiskDrives"]));
            }
            set {
                this["InhDefaultRedirectDiskDrives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectKeys {
            get {
                return ((bool)(this["InhDefaultRedirectKeys"]));
            }
            set {
                this["InhDefaultRedirectKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectPorts {
            get {
                return ((bool)(this["InhDefaultRedirectPorts"]));
            }
            set {
                this["InhDefaultRedirectPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectPrinters {
            get {
                return ((bool)(this["InhDefaultRedirectPrinters"]));
            }
            set {
                this["InhDefaultRedirectPrinters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectSmartCards {
            get {
                return ((bool)(this["InhDefaultRedirectSmartCards"]));
            }
            set {
                this["InhDefaultRedirectSmartCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRedirectSound {
            get {
                return ((bool)(this["InhDefaultRedirectSound"]));
            }
            set {
                this["InhDefaultRedirectSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultResolution {
            get {
                return ((bool)(this["InhDefaultResolution"]));
            }
            set {
                this["InhDefaultResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUseConsoleSession {
            get {
                return ((bool)(this["InhDefaultUseConsoleSession"]));
            }
            set {
                this["InhDefaultUseConsoleSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUsername {
            get {
                return ((bool)(this["InhDefaultUsername"]));
            }
            set {
                this["InhDefaultUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultPanel {
            get {
                return ((bool)(this["InhDefaultPanel"]));
            }
            set {
                this["InhDefaultPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetHostnameLikeDisplayName {
            get {
                return ((bool)(this["SetHostnameLikeDisplayName"]));
            }
            set {
                this["SetHostnameLikeDisplayName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DoubleClickOnTabClosesIt {
            get {
                return ((bool)(this["DoubleClickOnTabClosesIt"]));
            }
            set {
                this["DoubleClickOnTabClosesIt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReconnectOnDisconnect {
            get {
                return ((bool)(this["ReconnectOnDisconnect"]));
            }
            set {
                this["ReconnectOnDisconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowPanelSelectionDlg {
            get {
                return ((bool)(this["AlwaysShowPanelSelectionDlg"]));
            }
            set {
                this["AlwaysShowPanelSelectionDlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeToTray {
            get {
                return ((bool)(this["MinimizeToTray"]));
            }
            set {
                this["MinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleClickSwitchesToOpenConnection {
            get {
                return ((bool)(this["SingleClickSwitchesToOpenConnection"]));
            }
            set {
                this["SingleClickSwitchesToOpenConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NoAuth")]
        public string ConDefaultRDPAuthenticationLevel {
            get {
                return ((string)(this["ConDefaultRDPAuthenticationLevel"]));
            }
            set {
                this["ConDefaultRDPAuthenticationLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDPAuthenticationLevel {
            get {
                return ((bool)(this["InhDefaultRDPAuthenticationLevel"]));
            }
            set {
                this["InhDefaultRDPAuthenticationLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultMacAddress {
            get {
                return ((string)(this["ConDefaultMacAddress"]));
            }
            set {
                this["ConDefaultMacAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultMacAddress {
            get {
                return ((bool)(this["InhDefaultMacAddress"]));
            }
            set {
                this["InhDefaultMacAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EncryptCompleteConnectionsFile {
            get {
                return ((bool)(this["EncryptCompleteConnectionsFile"]));
            }
            set {
                this["EncryptCompleteConnectionsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultUserField {
            get {
                return ((string)(this["ConDefaultUserField"]));
            }
            set {
                this["ConDefaultUserField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUserField {
            get {
                return ((bool)(this["InhDefaultUserField"]));
            }
            set {
                this["InhDefaultUserField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Never")]
        public string ConDefaultRDGatewayUsageMethod {
            get {
                return ((string)(this["ConDefaultRDGatewayUsageMethod"]));
            }
            set {
                this["ConDefaultRDGatewayUsageMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yes")]
        public string ConDefaultRDGatewayUseConnectionCredentials {
            get {
                return ((string)(this["ConDefaultRDGatewayUseConnectionCredentials"]));
            }
            set {
                this["ConDefaultRDGatewayUseConnectionCredentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mRemoteUG")]
        public string ConDefaultIcon {
            get {
                return ((string)(this["ConDefaultIcon"]));
            }
            set {
                this["ConDefaultIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayUsageMethod {
            get {
                return ((bool)(this["InhDefaultRDGatewayUsageMethod"]));
            }
            set {
                this["InhDefaultRDGatewayUsageMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayHostname {
            get {
                return ((bool)(this["InhDefaultRDGatewayHostname"]));
            }
            set {
                this["InhDefaultRDGatewayHostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayUsername {
            get {
                return ((bool)(this["InhDefaultRDGatewayUsername"]));
            }
            set {
                this["InhDefaultRDGatewayUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayPassword {
            get {
                return ((bool)(this["InhDefaultRDGatewayPassword"]));
            }
            set {
                this["InhDefaultRDGatewayPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayDomain {
            get {
                return ((bool)(this["InhDefaultRDGatewayDomain"]));
            }
            set {
                this["InhDefaultRDGatewayDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDGatewayUseConnectionCredentials {
            get {
                return ((bool)(this["InhDefaultRDGatewayUseConnectionCredentials"]));
            }
            set {
                this["InhDefaultRDGatewayUseConnectionCredentials"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int RdpReconnectionCount {
            get {
                return ((int)(this["RdpReconnectionCount"]));
            }
            set {
                this["RdpReconnectionCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System")]
        public global::mRemoteUG.UI.UiTheme UiTheme {
            get {
                return ((global::mRemoteUG.UI.UiTheme)(this["UiTheme"]));
            }
            set {
                this["UiTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDGatewayHostname {
            get {
                return ((string)(this["ConDefaultRDGatewayHostname"]));
            }
            set {
                this["ConDefaultRDGatewayHostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDGatewayUsername {
            get {
                return ((string)(this["ConDefaultRDGatewayUsername"]));
            }
            set {
                this["ConDefaultRDGatewayUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDGatewayPassword {
            get {
                return ((string)(this["ConDefaultRDGatewayPassword"]));
            }
            set {
                this["ConDefaultRDGatewayPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultRDGatewayDomain {
            get {
                return ((string)(this["ConDefaultRDGatewayDomain"]));
            }
            set {
                this["ConDefaultRDGatewayDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultEnableFontSmoothing {
            get {
                return ((bool)(this["ConDefaultEnableFontSmoothing"]));
            }
            set {
                this["ConDefaultEnableFontSmoothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultEnableFontSmoothing {
            get {
                return ((bool)(this["InhDefaultEnableFontSmoothing"]));
            }
            set {
                this["InhDefaultEnableFontSmoothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultEnableDesktopComposition {
            get {
                return ((bool)(this["ConDefaultEnableDesktopComposition"]));
            }
            set {
                this["ConDefaultEnableDesktopComposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultEnableDesktopComposition {
            get {
                return ((bool)(this["InhDefaultEnableDesktopComposition"]));
            }
            set {
                this["InhDefaultEnableDesktopComposition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ConfirmCloseConnection {
            get {
                return ((int)(this["ConfirmCloseConnection"]));
            }
            set {
                this["ConfirmCloseConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Size MainFormRestoreSize {
            get {
                return ((global::System.Drawing.Size)(this["MainFormRestoreSize"]));
            }
            set {
                this["MainFormRestoreSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Point MainFormRestoreLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormRestoreLocation"]));
            }
            set {
                this["MainFormRestoreLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool BackupFileEnabled {
            get {
                return ((bool)(this["BackupFileEnabled"]));
            }
            set {
                this["BackupFileEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public int BackupFileKeepCount {
            get {
                return ((int)(this["BackupFileKeepCount"]));
            }
            set {
                this["BackupFileKeepCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}.{1:yyyyMMdd-HHmmssffff}.backup")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string BackupFileNameFormat {
            get {
                return ((string)(this["BackupFileNameFormat"]));
            }
            set {
                this["BackupFileNameFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultUseCredSsp {
            get {
                return ((bool)(this["InhDefaultUseCredSsp"]));
            }
            set {
                this["InhDefaultUseCredSsp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConDefaultUseCredSsp {
            get {
                return ((bool)(this["ConDefaultUseCredSsp"]));
            }
            set {
                this["ConDefaultUseCredSsp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool AlwaysShowPanelTabs {
            get {
                return ((bool)(this["AlwaysShowPanelTabs"]));
            }
            set {
                this["AlwaysShowPanelTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public bool IdentifyQuickConnectTabs {
            get {
                return ((bool)(this["IdentifyQuickConnectTabs"]));
            }
            set {
                this["IdentifyQuickConnectTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowConfigHelpText {
            get {
                return ((bool)(this["ShowConfigHelpText"]));
            }
            set {
                this["ShowConfigHelpText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PuttySavedSessionsPanel {
            get {
                return ((string)(this["PuttySavedSessionsPanel"]));
            }
            set {
                this["PuttySavedSessionsPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultLoadBalanceInfo {
            get {
                return ((string)(this["ConDefaultLoadBalanceInfo"]));
            }
            set {
                this["ConDefaultLoadBalanceInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConDefaultAutomaticResize {
            get {
                return ((bool)(this["ConDefaultAutomaticResize"]));
            }
            set {
                this["ConDefaultAutomaticResize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultLoadBalanceInfo {
            get {
                return ((bool)(this["InhDefaultLoadBalanceInfo"]));
            }
            set {
                this["InhDefaultLoadBalanceInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultAutomaticResize {
            get {
                return ((bool)(this["InhDefaultAutomaticResize"]));
            }
            set {
                this["InhDefaultAutomaticResize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RDP")]
        [global::System.Configuration.SettingsManageabilityAttribute(global::System.Configuration.SettingsManageability.Roaming)]
        public string QuickConnectProtocol {
            get {
                return ((string)(this["QuickConnectProtocol"]));
            }
            set {
                this["QuickConnectProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCompleteConsPathInTitle {
            get {
                return ((bool)(this["ShowCompleteConsPathInTitle"]));
            }
            set {
                this["ShowCompleteConsPathInTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ConRDPOverallConnectionTimeout {
            get {
                return ((int)(this["ConRDPOverallConnectionTimeout"]));
            }
            set {
                this["ConRDPOverallConnectionTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int EncryptionKeyDerivationIterations {
            get {
                return ((int)(this["EncryptionKeyDerivationIterations"]));
            }
            set {
                this["EncryptionKeyDerivationIterations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dynamic")]
        public string ConDefaultSoundQuality {
            get {
                return ((string)(this["ConDefaultSoundQuality"]));
            }
            set {
                this["ConDefaultSoundQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultSoundQuality {
            get {
                return ((bool)(this["InhDefaultSoundQuality"]));
            }
            set {
                this["InhDefaultSoundQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ConDefaultRDPMinutesToIdleTimeout {
            get {
                return ((int)(this["ConDefaultRDPMinutesToIdleTimeout"]));
            }
            set {
                this["ConDefaultRDPMinutesToIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDPMinutesToIdleTimeout {
            get {
                return ((bool)(this["InhDefaultRDPMinutesToIdleTimeout"]));
            }
            set {
                this["InhDefaultRDPMinutesToIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ConDefaultRDPAlertIdleTimeout {
            get {
                return ((bool)(this["ConDefaultRDPAlertIdleTimeout"]));
            }
            set {
                this["ConDefaultRDPAlertIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InhDefaultRDPAlertIdleTimeout {
            get {
                return ((bool)(this["InhDefaultRDPAlertIdleTimeout"]));
            }
            set {
                this["InhDefaultRDPAlertIdleTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogFilePath {
            get {
                return ((string)(this["LogFilePath"]));
            }
            set {
                this["LogFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextLogMessageWriterWriteDebugMsgs {
            get {
                return ((bool)(this["TextLogMessageWriterWriteDebugMsgs"]));
            }
            set {
                this["TextLogMessageWriterWriteDebugMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextLogMessageWriterWriteInfoMsgs {
            get {
                return ((bool)(this["TextLogMessageWriterWriteInfoMsgs"]));
            }
            set {
                this["TextLogMessageWriterWriteInfoMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextLogMessageWriterWriteWarningMsgs {
            get {
                return ((bool)(this["TextLogMessageWriterWriteWarningMsgs"]));
            }
            set {
                this["TextLogMessageWriterWriteWarningMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TextLogMessageWriterWriteErrorMsgs {
            get {
                return ((bool)(this["TextLogMessageWriterWriteErrorMsgs"]));
            }
            set {
                this["TextLogMessageWriterWriteErrorMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotificationPanelWriterWriteDebugMsgs {
            get {
                return ((bool)(this["NotificationPanelWriterWriteDebugMsgs"]));
            }
            set {
                this["NotificationPanelWriterWriteDebugMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NotificationPanelWriterWriteInfoMsgs {
            get {
                return ((bool)(this["NotificationPanelWriterWriteInfoMsgs"]));
            }
            set {
                this["NotificationPanelWriterWriteInfoMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotificationPanelWriterWriteWarningMsgs {
            get {
                return ((bool)(this["NotificationPanelWriterWriteWarningMsgs"]));
            }
            set {
                this["NotificationPanelWriterWriteWarningMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotificationPanelWriterWriteErrorMsgs {
            get {
                return ((bool)(this["NotificationPanelWriterWriteErrorMsgs"]));
            }
            set {
                this["NotificationPanelWriterWriteErrorMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopupMessageWriterWriteDebugMsgs {
            get {
                return ((bool)(this["PopupMessageWriterWriteDebugMsgs"]));
            }
            set {
                this["PopupMessageWriterWriteDebugMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopupMessageWriterWriteInfoMsgs {
            get {
                return ((bool)(this["PopupMessageWriterWriteInfoMsgs"]));
            }
            set {
                this["PopupMessageWriterWriteInfoMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopupMessageWriterWriteWarningMsgs {
            get {
                return ((bool)(this["PopupMessageWriterWriteWarningMsgs"]));
            }
            set {
                this["PopupMessageWriterWriteWarningMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PopupMessageWriterWriteErrorMsgs {
            get {
                return ((bool)(this["PopupMessageWriterWriteErrorMsgs"]));
            }
            set {
                this["PopupMessageWriterWriteErrorMsgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LogToApplicationDirectory {
            get {
                return ((bool)(this["LogToApplicationDirectory"]));
            }
            set {
                this["LogToApplicationDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultUsername {
            get {
                return ((string)(this["ConDefaultUsername"]));
            }
            set {
                this["ConDefaultUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultPassword {
            get {
                return ((string)(this["ConDefaultPassword"]));
            }
            set {
                this["ConDefaultPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConDefaultDomain {
            get {
                return ((string)(this["ConDefaultDomain"]));
            }
            set {
                this["ConDefaultDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("General")]
        public string ConDefaultPanel {
            get {
                return ((string)(this["ConDefaultPanel"]));
            }
            set {
                this["ConDefaultPanel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveConnectionsAfterEveryEdit {
            get {
                return ((bool)(this["SaveConnectionsAfterEveryEdit"]));
            }
            set {
                this["SaveConnectionsAfterEveryEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseFilterSearch {
            get {
                return ((bool)(this["UseFilterSearch"]));
            }
            set {
                this["UseFilterSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LockToolbars {
            get {
                return ((bool)(this["LockToolbars"]));
            }
            set {
                this["LockToolbars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RdpLoadBalanceInfoUseUtf8 {
            get {
                return ((bool)(this["RdpLoadBalanceInfoUseUtf8"]));
            }
            set {
                this["RdpLoadBalanceInfoUseUtf8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CreateEmptyPanelOnStartUp {
            get {
                return ((bool)(this["CreateEmptyPanelOnStartUp"]));
            }
            set {
                this["CreateEmptyPanelOnStartUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("General")]
        public string StartUpPanelName {
            get {
                return ((string)(this["StartUpPanelName"]));
            }
            set {
                this["StartUpPanelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OverrideFIPSCheck {
            get {
                return ((bool)(this["OverrideFIPSCheck"]));
            }
            set {
                this["OverrideFIPSCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainLayoutLeftColumnWidth {
            get {
                return ((int)(this["MainLayoutLeftColumnWidth"]));
            }
            set {
                this["MainLayoutLeftColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainLayoutTreeSharePermille {
            get {
                return ((int)(this["MainLayoutTreeSharePermille"]));
            }
            set {
                this["MainLayoutTreeSharePermille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainLayoutNotificationsSharePermille {
            get {
                return ((int)(this["MainLayoutNotificationsSharePermille"]));
            }
            set {
                this["MainLayoutNotificationsSharePermille"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainLayoutShowTree {
            get {
                return ((bool)(this["MainLayoutShowTree"]));
            }
            set {
                this["MainLayoutShowTree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainLayoutShowConfig {
            get {
                return ((bool)(this["MainLayoutShowConfig"]));
            }
            set {
                this["MainLayoutShowConfig"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainLayoutShowNotifications {
            get {
                return ((bool)(this["MainLayoutShowNotifications"]));
            }
            set {
                this["MainLayoutShowNotifications"] = value;
            }
        }
    }
}
