using System.Text;
using SkiaSharp;

namespace IconGen;

/// <summary>Generates the C# the application compiles against, and a sheet a human can look at.</summary>
public static class Emit
{
    /// <summary>
    /// The replacement for what Properties\Resources.resx used to generate.
    /// </summary>
    /// <remarks>
    /// Same class name, same namespace, same member names, so every existing `Resources.Foo` call
    /// site compiles untouched - including the six in .Designer.cs files, which must not be opened
    /// in the designer to be edited. What changes is only what backs them.
    /// <para>
    /// A glyph member hands back the 16px frame. Menus are built before any DPI is known and the
    /// DPI pass re-picks immediately afterwards, so there is one place that decides size and it is
    /// not here.
    /// </para>
    /// </remarks>
    public static string ResourcesClass(Manifest manifest)
    {
        var text = new StringBuilder();
        text.Append("""
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     Generated by Tools/IconGen from src/mRemoteUG/Resources/icon-manifest.json.
            //     Edits here are lost on the next run. Change the manifest instead.
            // </auto-generated>
            //------------------------------------------------------------------------------

            using System.Drawing;
            using mRemoteUG.UI;

            namespace mRemoteUG
            {
                /// <summary>The artwork this application ships, by name.</summary>
                internal static class Resources
                {

            """);

        foreach (var entry in manifest.Glyphs.OrderBy(g => g.Name, StringComparer.Ordinal))
        {
            if (entry.Note is { } note)
                text.AppendLine($"        /// <summary>{Escape(note)}</summary>");
            text.AppendLine($"        internal static Bitmap {entry.Name} => Glyphs.Get(\"{entry.Name}\", Glyphs.LogicalSize);");
        }

        text.AppendLine();
        foreach (var entry in manifest.WindowIcons.OrderBy(w => w.Name, StringComparer.Ordinal))
            text.AppendLine($"        internal static Icon {entry.Name} => WindowIcons.Get(\"{entry.Name}\");");


        text.AppendLine();
        text.AppendLine("        /// <summary>Every glyph name the manifest declares.</summary>");
        text.AppendLine("        internal static readonly string[] GlyphNames =");
        text.AppendLine("        {");
        foreach (var entry in manifest.Glyphs.OrderBy(g => g.Name, StringComparer.Ordinal))
            text.AppendLine($"            \"{entry.Name}\",");
        text.AppendLine("        };");

        text.AppendLine();
        text.AppendLine("        /// <summary>Glyphs that carry meaning in their colour and are never tinted.</summary>");
        text.AppendLine("        internal static readonly string[] FixedColourGlyphs =");
        text.AppendLine("        {");
        foreach (var entry in manifest.Glyphs.Where(g => g.Tint is Tint.Fixed).OrderBy(g => g.Name, StringComparer.Ordinal))
            text.AppendLine($"            \"{entry.Name}\",");
        text.AppendLine("        };");

        text.AppendLine();
        text.AppendLine("        /// <summary>Connection icon names from older builds, and what each heals to.</summary>");
        text.AppendLine("        internal static readonly System.Collections.Generic.Dictionary<string, string> LegacyConnectionIcons =");
        text.AppendLine("            new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal)");
        text.AppendLine("        {");
        foreach (var entry in manifest.ConnectionIcons.OrderBy(c => c.Name, StringComparer.Ordinal))
            foreach (var legacy in entry.Legacy.OrderBy(l => l, StringComparer.Ordinal))
                text.AppendLine($"            [\"{legacy}\"] = \"{entry.Name}\",");
        text.AppendLine("        };");

        text.Append("""
                }
            }

            """);

        return text.ToString().ReplaceLineEndings("\r\n");
    }

    private static string Escape(string s) =>
        s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    /// <summary>
    /// Every glyph at 32px on one canvas, light row and dark row, so the set can be reviewed by
    /// eye. A diff of 500 PNGs is unreadable, and no test can say whether a mark reads as its name.
    /// </summary>
    public static void ContactSheet(Manifest manifest, Catalogue catalogue, string path)
    {
        const int cell = 48, icon = 32, cols = 12, pad = (cell - icon) / 2;
        var entries = manifest.All().OrderBy(e => e.Shape).ThenBy(e => e.Entry.Name, StringComparer.Ordinal).ToList();
        var rows = (entries.Count + cols - 1) / cols;

        using var bitmap = new SKBitmap(cols * cell, rows * cell * 2, SKColorType.Rgba8888, SKAlphaType.Unpremul);
        using var canvas = new SKCanvas(bitmap);
        canvas.Clear(new SKColor(0xF3, 0xF3, 0xF3));
        canvas.DrawRect(0, rows * cell, bitmap.Width, rows * cell, new SKPaint { Color = new SKColor(0x20, 0x20, 0x20) });

        for (var i = 0; i < entries.Count; i++)
        {
            var (entry, _) = entries[i];
            var source = catalogue.SourceSizeFor(entry.Style, entry.Fluent, icon);
            var markup = catalogue.Content(entry.Style, entry.Fluent, source);

            foreach (var (dark, colour) in new[]
                     {
                         (false, entry.Tint is Tint.Mask ? new SKColor(0x1F, 0x1F, 0x1F) : SKColor.Parse(entry.Color!)),
                         (true,  entry.Tint is Tint.Mask ? new SKColor(0xFF, 0xFF, 0xFF) : SKColor.Parse(entry.Color!))
                     })
            {
                var png = Renderer.ToPng(markup, source, icon, colour, entry.Badge);
                using var frame = SKBitmap.Decode(png);
                var x = (i % cols) * cell + pad;
                var y = (i / cols) * cell + pad + (dark ? rows * cell : 0);
                canvas.DrawBitmap(frame, x, y);
            }
        }

        using var image = SKImage.FromBitmap(bitmap);
        using var data = image.Encode(SKEncodedImageFormat.Png, 100);
        File.WriteAllBytes(path, data.ToArray());
    }
}
