//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by Tools/IconGen from src/mRemoteUG/Resources/icon-manifest.json.
//     Edits here are lost on the next run. Change the manifest instead.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing;
using mRemoteUG.UI;

namespace mRemoteUG
{
    /// <summary>The artwork this application ships, by name.</summary>
    internal static class Resources
    {
        /// <summary>The About menu item. Named for what it opens: the application ships no brand mark to put here.</summary>
        internal static Bitmap About => Glyphs.Get("About", Glyphs.LogicalSize);
        internal static Bitmap Arrow_Down => Glyphs.Get("Arrow_Down", Glyphs.LogicalSize);
        internal static Bitmap Arrow_Up => Glyphs.Get("Arrow_Up", Glyphs.LogicalSize);
        /// <summary>The property grid sort toggle. Replaces a framework bitmap, not a Silk one - see ConfigWindow.StyleFrameworkSortButtons.</summary>
        internal static Bitmap Categorized => Glyphs.Get("Categorized", Glyphs.LogicalSize);
        internal static Bitmap Chat => Glyphs.Get("Chat", Glyphs.LogicalSize);
        internal static Bitmap Collapse => Glyphs.Get("Collapse", Glyphs.LogicalSize);
        /// <summary>Composited onto a connected node icon by StatusImageList.Overlay, so it is generated inset into the corner rather than full-bleed.</summary>
        internal static Bitmap ConnectedOverlay => Glyphs.Get("ConnectedOverlay", Glyphs.LogicalSize);
        /// <summary>A bare plus, not a plug: monitor_go already draws PlugConnected, and two menu items with the same mark is worse than a generic one.</summary>
        internal static Bitmap Connection_Add => Glyphs.Get("Connection_Add", Glyphs.LogicalSize);
        internal static Bitmap Connections_Load => Glyphs.Get("Connections_Load", Glyphs.LogicalSize);
        internal static Bitmap Connections_New => Glyphs.Get("Connections_New", Glyphs.LogicalSize);
        internal static Bitmap Connections_Save => Glyphs.Get("Connections_Save", Glyphs.LogicalSize);
        /// <summary>Save in the filled weight. SaveEdit and SaveCopy both start at 20, and 16 is the size this is drawn at.</summary>
        internal static Bitmap Connections_SaveAs => Glyphs.Get("Connections_SaveAs", Glyphs.LogicalSize);
        internal static Bitmap Copy => Glyphs.Get("Copy", Glyphs.LogicalSize);
        internal static Bitmap Delete => Glyphs.Get("Delete", Glyphs.LogicalSize);
        internal static Bitmap Error => Glyphs.Get("Error", Glyphs.LogicalSize);
        internal static Bitmap ErrorSmall => Glyphs.Get("ErrorSmall", Glyphs.LogicalSize);
        internal static Bitmap ErrorsAndInfos => Glyphs.Get("ErrorsAndInfos", Glyphs.LogicalSize);
        internal static Bitmap Expand => Glyphs.Get("Expand", Glyphs.LogicalSize);
        /// <summary>The tab context menu. Was base64 inside ConnectionWindow.resx rather than a file, which is why it is missing from every count of the artwork.</summary>
        internal static Bitmap ExternalApps => Glyphs.Get("ExternalApps", Glyphs.LogicalSize);
        internal static Bitmap Folder => Glyphs.Get("Folder", Glyphs.LogicalSize);
        internal static Bitmap Folder_Add => Glyphs.Get("Folder_Add", Glyphs.LogicalSize);
        internal static Bitmap HostStatus_Check => Glyphs.Get("HostStatus_Check", Glyphs.LogicalSize);
        internal static Bitmap HostStatus_Off => Glyphs.Get("HostStatus_Off", Glyphs.LogicalSize);
        internal static Bitmap HostStatus_On => Glyphs.Get("HostStatus_On", Glyphs.LogicalSize);
        internal static Bitmap Information => Glyphs.Get("Information", Glyphs.LogicalSize);
        internal static Bitmap InformationSmall => Glyphs.Get("InformationSmall", Glyphs.LogicalSize);
        internal static Bitmap Inheritance => Glyphs.Get("Inheritance", Glyphs.LogicalSize);
        /// <summary>The _Default half of the pair is the filled weight, which is what Fluent uses for a set state.</summary>
        internal static Bitmap Inheritance_Default => Glyphs.Get("Inheritance_Default", Glyphs.LogicalSize);
        internal static Bitmap JumpTo => Glyphs.Get("JumpTo", Glyphs.LogicalSize);
        internal static Bitmap Keyboard => Glyphs.Get("Keyboard", Glyphs.LogicalSize);
        internal static Bitmap Lock => Glyphs.Get("Lock", Glyphs.LogicalSize);
        internal static Bitmap Options => Glyphs.Get("Options", Glyphs.LogicalSize);
        internal static Bitmap Panel_Add => Glyphs.Get("Panel_Add", Glyphs.LogicalSize);
        internal static Bitmap Panels => Glyphs.Get("Panels", Glyphs.LogicalSize);
        internal static Bitmap Pause => Glyphs.Get("Pause", Glyphs.LogicalSize);
        internal static Bitmap Play => Glyphs.Get("Play", Glyphs.LogicalSize);
        internal static Bitmap Play_Quick => Glyphs.Get("Play_Quick", Glyphs.LogicalSize);
        internal static Bitmap Properties => Glyphs.Get("Properties", Glyphs.LogicalSize);
        /// <summary>Pairs with Properties the way Inheritance_Default pairs with Inheritance.</summary>
        internal static Bitmap Properties_Default => Glyphs.Get("Properties_Default", Glyphs.LogicalSize);
        internal static Bitmap PuttyConfig => Glyphs.Get("PuttyConfig", Glyphs.LogicalSize);
        internal static Bitmap PuttySessions => Glyphs.Get("PuttySessions", Glyphs.LogicalSize);
        internal static Bitmap Quit => Glyphs.Get("Quit", Glyphs.LogicalSize);
        internal static Bitmap RDP => Glyphs.Get("RDP", Glyphs.LogicalSize);
        internal static Bitmap Refresh => Glyphs.Get("Refresh", Glyphs.LogicalSize);
        internal static Bitmap Rename => Glyphs.Get("Rename", Glyphs.LogicalSize);
        internal static Bitmap Root => Glyphs.Get("Root", Glyphs.LogicalSize);
        internal static Bitmap SSHTransfer => Glyphs.Get("SSHTransfer", Glyphs.LogicalSize);
        internal static Bitmap Search => Glyphs.Get("Search", Glyphs.LogicalSize);
        internal static Bitmap SmartSize => Glyphs.Get("SmartSize", Glyphs.LogicalSize);
        internal static Bitmap Sort_AZ => Glyphs.Get("Sort_AZ", Glyphs.LogicalSize);
        internal static Bitmap Sort_ZA => Glyphs.Get("Sort_ZA", Glyphs.LogicalSize);
        /// <summary>The property grid NoSort button, which WinForms ships with no text, no tooltip and the same bitmap as Alphabetical.</summary>
        internal static Bitmap Unsorted => Glyphs.Get("Unsorted", Glyphs.LogicalSize);
        internal static Bitmap View => Glyphs.Get("View", Glyphs.LogicalSize);
        internal static Bitmap Warning => Glyphs.Get("Warning", Glyphs.LogicalSize);
        internal static Bitmap WarningSmall => Glyphs.Get("WarningSmall", Glyphs.LogicalSize);
        internal static Bitmap application_side_tree => Glyphs.Get("application_side_tree", Glyphs.LogicalSize);
        internal static Bitmap arrow_out => Glyphs.Get("arrow_out", Glyphs.LogicalSize);
        /// <summary>The lowest notification class. The Silk brick meant nothing in particular; a bug does.</summary>
        internal static Bitmap brick => Glyphs.Get("brick", Glyphs.LogicalSize);
        internal static Bitmap cog => Glyphs.Get("cog", Glyphs.LogicalSize);
        /// <summary>KeyReset is the exact mark but starts at 20; the delete is carried by the menu text.</summary>
        internal static Bitmap key_delete => Glyphs.Get("key_delete", Glyphs.LogicalSize);
        internal static Bitmap monitor_delete => Glyphs.Get("monitor_delete", Glyphs.LogicalSize);
        internal static Bitmap monitor_go => Glyphs.Get("monitor_go", Glyphs.LogicalSize);
        internal static Bitmap page_copy => Glyphs.Get("page_copy", Glyphs.LogicalSize);

        internal static Icon App_Icon => WindowIcons.Get("App_Icon");
        internal static Icon Config_Icon => WindowIcons.Get("Config_Icon");
        internal static Icon Connections_SaveAs_Icon => WindowIcons.Get("Connections_SaveAs_Icon");
        internal static Icon Info_Icon => WindowIcons.Get("Info_Icon");
        internal static Icon Panels_Icon => WindowIcons.Get("Panels_Icon");
        internal static Icon Root_Icon => WindowIcons.Get("Root_Icon");

        /// <summary>Every glyph name the manifest declares.</summary>
        internal static readonly string[] GlyphNames =
        {
            "About",
            "Arrow_Down",
            "Arrow_Up",
            "Categorized",
            "Chat",
            "Collapse",
            "ConnectedOverlay",
            "Connection_Add",
            "Connections_Load",
            "Connections_New",
            "Connections_Save",
            "Connections_SaveAs",
            "Copy",
            "Delete",
            "Error",
            "ErrorSmall",
            "ErrorsAndInfos",
            "Expand",
            "ExternalApps",
            "Folder",
            "Folder_Add",
            "HostStatus_Check",
            "HostStatus_Off",
            "HostStatus_On",
            "Information",
            "InformationSmall",
            "Inheritance",
            "Inheritance_Default",
            "JumpTo",
            "Keyboard",
            "Lock",
            "Options",
            "Panel_Add",
            "Panels",
            "Pause",
            "Play",
            "Play_Quick",
            "Properties",
            "Properties_Default",
            "PuttyConfig",
            "PuttySessions",
            "Quit",
            "RDP",
            "Refresh",
            "Rename",
            "Root",
            "SSHTransfer",
            "Search",
            "SmartSize",
            "Sort_AZ",
            "Sort_ZA",
            "Unsorted",
            "View",
            "Warning",
            "WarningSmall",
            "application_side_tree",
            "arrow_out",
            "brick",
            "cog",
            "key_delete",
            "monitor_delete",
            "monitor_go",
            "page_copy",
        };

        /// <summary>Glyphs that carry meaning in their colour and are never tinted.</summary>
        internal static readonly string[] FixedColourGlyphs =
        {
            "ConnectedOverlay",
            "Error",
            "ErrorSmall",
            "HostStatus_Check",
            "HostStatus_Off",
            "HostStatus_On",
            "Information",
            "InformationSmall",
            "Warning",
            "WarningSmall",
        };

        /// <summary>Connection icon names from older builds, and what each heals to.</summary>
        internal static readonly System.Collections.Generic.Dictionary<string, string> LegacyConnectionIcons =
            new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.Ordinal)
        {
            ["Anti Virus"] = "Firewall",
            ["Tel"] = "Phone",
            ["Fax"] = "Printer",
            ["Terminal Server"] = "Remote Desktop",
            ["Workstation"] = "Remote Desktop",
            ["Telnet"] = "SSH",
            ["Build Server"] = "Server",
            ["Finance"] = "Server",
            ["Log"] = "Server",
            ["Test Server"] = "Server",
            ["Backup"] = "Storage",
            ["ESX"] = "Virtual Machine",
            ["SharePoint"] = "Web Server",
            ["mRemote"] = "mRemoteUG",
        };
    }
}
