//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mRemoteUG.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mRemoteUG.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up the confCons_v2_9 connection file fixture.
        /// </summary>
        internal static string confCons_v2_9 {
            get {
                return ResourceManager.GetString("confCons_v2_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up the confCons_v2_9_5k_iterations connection file fixture.
        /// </summary>
        internal static string confCons_v2_9_5k_iterations {
            get {
                return ResourceManager.GetString("confCons_v2_9_5k_iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up the confCons_v2_9_fullencryption connection file fixture.
        /// </summary>
        internal static string confCons_v2_9_fullencryption {
            get {
                return ResourceManager.GetString("confCons_v2_9_fullencryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up the confCons_v2_9_passwordis_Password connection file fixture.
        /// </summary>
        internal static string confCons_v2_9_passwordis_Password {
            get {
                return ResourceManager.GetString("confCons_v2_9_passwordis_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up the confCons_v2_9_passwordis_Password_fullencryption connection file fixture.
        /// </summary>
        internal static string confCons_v2_9_passwordis_Password_fullencryption {
            get {
                return ResourceManager.GetString("confCons_v2_9_passwordis_Password_fullencryption", resourceCulture);
            }
        }

    }
}
