using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Reflection;
using mRemoteUG.UI;
using NUnit.Framework;

namespace mRemoteUG.Tests.UI
{
    /// <summary>
    /// Guards the artwork pipeline: that every glyph the manifest promises is actually embedded,
    /// at every size, and is the kind of image it says it is.
    /// </summary>
    /// <remarks>
    /// The PNGs are generated by Tools/IconGen and committed, so nothing about them is checked by
    /// the compiler. A name dropped from the manifest is a build error at the call site, which is
    /// the easy half; a name that is present but was never rendered at 48 pixels is invisible
    /// until a window opens on a 300% monitor. That is what these are for.
    /// <para>
    /// Whether a mark <em>reads</em> as its name is not testable and is not attempted here. That
    /// is the contact sheet, and a person looking at it.
    /// </para>
    /// </remarks>
    [TestFixture]
    public class GlyphTests
    {
        private static IEnumerable<string> GlyphNames => Resources.GlyphNames;

        /// <summary>
        /// Every glyph exists at every ladder size, and is that size.
        /// </summary>
        /// <remarks>
        /// One test over the whole grid rather than a case per cell. The grid is 61 x 8, and
        /// parameterising it put 488 cases into the run for what is a single assertion - a number
        /// that made the suite look far more thoroughly tested than it is. Assert.Multiple still
        /// names every glyph and size that failed, which was the only thing the cases bought.
        /// <para>
        /// The size is asserted, not merely that something came back. The connection icon test
        /// spent its life asserting non-null against artwork with one 16x16 frame, so it passed
        /// for a size that had never once been produced.
        /// </para>
        /// </remarks>
        [Test]
        public void EveryGlyphIsEmbeddedAtEveryLadderSizeAndIsThatSize()
        {
            Assert.Multiple(() =>
            {
                foreach (var name in Resources.GlyphNames)
                    foreach (var size in Glyphs.Ladder)
                    {
                        // Caught rather than allowed to propagate: a missing glyph throws out of
                        // the loader, and a throw escapes Assert.Multiple, so the first gap would
                        // hide every other one. Turning it into a failure keeps the whole grid
                        // reported in a single run, which is what the case-per-cell version gave.
                        try
                        {
                            var glyph = Glyphs.Get(name, size);
                            Assert.That(glyph.Size, Is.EqualTo(new Size(size, size)),
                                        $"the glyph \"{name}\" is embedded at {size} but is not square at it");
                        }
                        catch (InvalidOperationException ex)
                        {
                            Assert.Fail(ex.Message);
                        }
                    }
            });
        }

        /// <summary>
        /// A tintable glyph must ship colourless, or tinting it would be a no-op that silently
        /// keeps whatever colour was baked in.
        /// </summary>
        /// <remarks>
        /// Read from the raw embedded bytes rather than through <c>Glyphs.Get</c>, which tints on
        /// the way out - going through it would only ever prove that tinting works.
        /// </remarks>
        [Test]
        public void EveryTintableGlyphShipsAsAColourlessMask()
        {
            Assert.Multiple(() =>
            {
                foreach (var name in TintableGlyphs())
                {
                    using (var stream = new MemoryStream(Glyphs.RawBytes(name, Glyphs.LogicalSize)))
                    using (var bitmap = new Bitmap(stream))
                    {
                        var painted = Pixels(bitmap)
                            .Where(p => p.A > 0 && (p.R, p.G, p.B) != ((byte)255, (byte)255, (byte)255));

                        Assert.That(painted, Is.Empty,
                                    $"the glyph \"{name}\" is tintable but ships with colour " +
                                    "baked in, so the tint would be discarded");
                    }
                }
            });
        }

        [Test]
        public void ATintableGlyphComesBackInTheThemeForeground()
        {
            var tint = Glyphs.TintColor;

            Assert.Multiple(() =>
            {
                foreach (var name in TintableGlyphs())
                {
                    var coloured = Pixels(Glyphs.Get(name, Glyphs.LogicalSize))
                        .Where(p => p.A > 0).ToList();

                    Assert.That(coloured, Is.Not.Empty,
                                $"the glyph \"{name}\" is entirely transparent");
                    Assert.That(coloured.Where(p => (p.R, p.G, p.B) != (tint.R, tint.G, tint.B)), Is.Empty,
                                $"the glyph \"{name}\" was not tinted to the theme foreground");
                }
            });
        }

        [Test]
        public void AFixedColourGlyphIsNotTinted()
        {
            var tint = Glyphs.TintColor;

            Assert.Multiple(() =>
            {
                foreach (var name in FixedColourGlyphs())
                {
                    var coloured = Pixels(Glyphs.Get(name, Glyphs.LogicalSize))
                        .Where(p => p.A > 0).ToList();

                    Assert.That(coloured, Is.Not.Empty);

                    // An error is red whatever the theme is. If every pixel came back as the
                    // foreground, the fixed list and the tint pass have fallen out of step.
                    Assert.That(coloured.Any(p => (p.R, p.G, p.B) != (tint.R, tint.G, tint.B)),
                                $"the glyph \"{name}\" carries meaning in its colour but came " +
                                "back entirely in the theme foreground, so it was tinted");
                }
            });
        }

        /// <summary>
        /// The tint has to be a system colour, or it freezes at whatever was typed.
        /// </summary>
        /// <remarks>
        /// <c>IsSystemColor</c> rather than <c>IsKnownColor</c>, for the same reason ThemeTests
        /// says so: <c>Color.White</c> is known and is not a system colour.
        /// </remarks>
        [Test]
        public void TheTintIsTakenFromSystemColors()
        {
            Assert.That(Glyphs.TintColor.IsSystemColor, Is.True);
        }

        /// <summary>
        /// Every scale factor Windows offers has a ladder size at or above it.
        /// </summary>
        /// <remarks>
        /// 225% and 350% are the two that a ladder of 16/20/24/28/32/48 got wrong: 36 and 56
        /// device pixels, which snapped to 48 and to nothing respectively.
        /// </remarks>
        [TestCase(96), TestCase(120), TestCase(144), TestCase(168), TestCase(192),
         TestCase(216), TestCase(240), TestCase(288), TestCase(336), TestCase(384)]
        public void TheLadderCoversEveryScaleFactorWindowsOffers(int dpi)
        {
            var wanted = DpiScaling.Scale(16, dpi);
            var picked = Glyphs.LadderSizeFor(wanted);

            Assert.That(Glyphs.Ladder, Contains.Item(picked));
            Assert.That(picked, Is.GreaterThanOrEqualTo(wanted),
                        $"{dpi} DPI wants {wanted} pixels and the ladder offered {picked}, which is smaller");
        }

        [Test]
        public void TheLadderIsAscendingAndStartsAtTheLogicalSize()
        {
            Assert.Multiple(() =>
            {
                Assert.That(Glyphs.Ladder, Is.Ordered.Ascending);
                Assert.That(Glyphs.Ladder, Is.Unique);
                Assert.That(Glyphs.Ladder.First(), Is.EqualTo(Glyphs.LogicalSize));
            });
        }

        /// <summary>
        /// The cache hands back one instance per name and size.
        /// </summary>
        /// <remarks>
        /// Two things rest on this and both break quietly without it. Re-picking a ToolStripItem's
        /// glyph on a DPI change finds its name by reference identity, which needs the instance to
        /// be stable; and callers must not dispose what they are given, which is only safe to say
        /// because the instance is shared. See the remarks on <c>Glyphs.Get</c>.
        /// </remarks>
        [Test]
        public void TheCacheHandsBackTheSameInstanceForTheSameGlyph()
        {
            var first = Glyphs.Get("Folder", Glyphs.LogicalSize);
            var second = Glyphs.Get("Folder", Glyphs.LogicalSize);

            Assert.That(ReferenceEquals(first, second), Is.True);
        }

        [Test]
        public void AGlyphHandedOutByTheCacheCanBeRepickedAtAnotherSize()
        {
            var small = Glyphs.Get("Folder", 16);

            Assert.That(Glyphs.TryRepick(small, 32, out var large), Is.True);
            Assert.That(large.Size, Is.EqualTo(new Size(32, 32)));
            Assert.That(large, Is.SameAs(Glyphs.Get("Folder", 32)),
                        "re-picking went somewhere other than the cache");
        }

        [Test]
        public void AnImageThatDidNotComeFromTheCacheCannotBeRepicked()
        {
            using (var stranger = new Bitmap(16, 16))
            {
                Assert.That(Glyphs.TryRepick(stranger, 32, out _), Is.False);
                Assert.That(Glyphs.IsCached(stranger), Is.False);
            }
        }

        /// <summary>
        /// A connection icon re-picks like a glyph, because it comes out of the same cache.
        /// </summary>
        /// <remarks>
        /// That is what lets one DPI pass fix an icon-picker menu item and a File menu item with
        /// the same code, without either side knowing about the other.
        /// </remarks>
        [Test]
        public void AConnectionIconRepicksLikeAGlyph()
        {
            var icon = mRemoteUG.Connection.ConnectionIcon.FromString("Windows", 16);
            Assume.That(icon, Is.Not.Null);

            Assert.That(Glyphs.TryRepick(icon, 32, out var large), Is.True);
            Assert.That(large.Size, Is.EqualTo(new Size(32, 32)));
        }

        [Test]
        public void ARequestBetweenLadderSizesSnapsUp()
        {
            // Down would mean drawing a 20 pixel glyph into a 24 pixel slot.
            Assert.That(Glyphs.LadderSizeFor(21), Is.EqualTo(24));
            Assert.That(Glyphs.LadderSizeFor(16), Is.EqualTo(16));
        }

        [Test]
        public void ARequestPastTheTopOfTheLadderTakesTheLargest()
        {
            Assert.That(Glyphs.LadderSizeFor(4096), Is.EqualTo(Glyphs.Ladder.Last()));
        }

        /// <summary>
        /// Every member of the generated Resources class resolves.
        /// </summary>
        /// <remarks>
        /// Resources.g.cs is generated but committed, so a hand edit to it, or a manifest entry
        /// whose artwork never got written, compiles cleanly and throws when a window opens.
        /// </remarks>
        [Test]
        public void EveryGeneratedResourcesMemberResolves()
        {
            var members = typeof(Resources)
                .GetProperties(BindingFlags.Static | BindingFlags.NonPublic | BindingFlags.Public)
                .Where(p => p.CanRead);

            Assert.Multiple(() =>
            {
                foreach (var member in members)
                {
                    object value = null;
                    Assert.DoesNotThrow(() => value = member.GetValue(null), $"Resources.{member.Name} threw");
                    Assert.That(value, Is.Not.Null, $"Resources.{member.Name} resolved to null");
                }
            });
        }

        [Test]
        public void EveryWindowIconIsEmbeddedAndCarriesMoreThanOneFrame()
        {
            var names = WindowIcons.Names.ToList();
            Assume.That(names, Is.Not.Empty);

            Assert.Multiple(() =>
            {
                foreach (var name in names)
                {
                    var icon = WindowIcons.Get(name);
                    Assert.That(icon, Is.Not.Null, $"the window icon \"{name}\" did not resolve");

                    // A title bar icon that carries one frame is the thing this migration was
                    // about: Windows picks a frame, and with one to pick from it stretches.
                    using (var small = new Icon(icon, 16, 16))
                    using (var large = new Icon(icon, 48, 48))
                        Assert.That(small.Size, Is.Not.EqualTo(large.Size),
                                    $"the window icon \"{name}\" answers the same size for 16 and 48, " +
                                    "so it carries a single frame");
                }
            });
        }

        /// <summary>
        /// No upstream brand mark ships, in any shape.
        /// </summary>
        /// <remarks>
        /// The mRemoteNG logo was carried for a long time in three places at once - the
        /// executable icon, two window icons and the tray - and the last of them was only
        /// found by looking for the name rather than for a file. This asserts on the embedded
        /// resource names, so anything reintroducing it through any of the three globs fails
        /// here rather than shipping.
        /// </remarks>
        [Test]
        public void NoUpstreamBrandMarkIsEmbedded()
        {
            var branded = typeof(Glyphs).Assembly.GetManifestResourceNames()
                .Where(n => n.IndexOf("mRemote_Icon", StringComparison.OrdinalIgnoreCase) >= 0 ||
                            n.IndexOf("mRemoteNG", StringComparison.OrdinalIgnoreCase) >= 0)
                .ToList();

            Assert.That(branded, Is.Empty,
                        "the upstream brand mark is embedded again: " + string.Join(", ", branded));
        }

        /// <summary>
        /// The window icons are the five tool windows plus the application icon.
        /// </summary>
        /// <remarks>
        /// App_Icon is in this set because it is the same shape of artwork - a multi-frame
        /// .ico that Windows picks a frame from and that is never tinted - even though it is
        /// reached through the csproj rather than through Resources. Pinning the whole set is
        /// what catches artwork appearing or disappearing without the manifest saying so.
        /// </remarks>
        [Test]
        public void TheWindowIconsAreTheToolWindowOnesPlusTheApplicationIcon()
        {
            Assert.That(WindowIcons.Names, Is.EquivalentTo(new[]
            {
                "App_Icon",
                "Config_Icon", "Connections_SaveAs_Icon", "Info_Icon", "Panels_Icon", "Root_Icon"
            }));
        }

        private static IEnumerable<string> TintableGlyphs() =>
            GlyphNames.Where(n => !Resources.FixedColourGlyphs.Contains(n));

        private static IEnumerable<string> FixedColourGlyphs() => Resources.FixedColourGlyphs;

        private static IEnumerable<Color> Pixels(Bitmap bitmap)
        {
            for (var y = 0; y < bitmap.Height; y++)
                for (var x = 0; x < bitmap.Width; x++)
                    yield return bitmap.GetPixel(x, y);
        }
    }
}
